Lite 21975 Redesign of EaaS websocket channel data models
cloudblue/connect-eaas-core pull request #1
Opened 2022-02-01 12:16 UTC by bdjilka

- skeleton of project
- new design of ws data models
- backwards capability (function to transform old schemas to new ones)

PR is open to discuss naming of new models, its attributes and nesting content.

2022-02-02 15:28 UTC, ffaraoneim requested changes
Small changes are needed.
I miss a function to transform from v2 to v1 because we need it to respond to legacy runners.

2022-02-02 15:28 UTC, ffaraoneim commented on demo.py
> +# from connect.eaas.core.dataclasses import MessageType
Please remove this file

2022-02-02 15:28 UTC, ffaraoneim commented on pyproject.toml
> +lark-parser = "0.11.0"
This dependency is not needed, please remove it

2022-02-02 15:28 UTC, ffaraoneim commented on pyproject.toml
> +cachetools = "^5.0.0"
This one also, not needed, please remove

2022-02-02 17:44 UTC, bdjilka commented on connect/eaas/core/dataclasses.py
> +class TaskPayload(BaseModel):
In my opinion, for consistency we should name all types of Message's model 'data' attribute the same way. So as 'Payload' in naming has place to be and plus/minus represent the meaning, maybe to leave 'TaskPayload'?

2022-02-02 17:46 UTC, bdjilka commented
> I miss a function to transform from v2 to v1 because we need it to respond to legacy runners.

Ooops, missed it. Of course will implement.

2022-02-02 17:51 UTC, bdjilka commented on connect/eaas/core/dataclasses.py
> +class ExtensionPayload(BaseModel):
Find it a bad naming :( Thought a lot about it, another variants were - 'ExtentionSetup', 'ExtentionConfiguration', simply 'Configuration' and 'Specification'

2022-02-03 07:58 UTC, ffaraoneim requested changes

2022-02-03 07:58 UTC, ffaraoneim commented on connect/eaas/core/dataclasses.py
> +class TaskPayload(BaseModel):
Ok!

2022-02-03 07:58 UTC, ffaraoneim commented on connect/eaas/core/dataclasses.py
> +class ExtensionPayload(BaseModel):
Ok let it ExtensionPayload

2022-02-03 13:17 UTC, merged