Add transformation extensions
cloudblue/connect-eaas-core pull request #47
Opened 2022-11-03 14:51 UTC by bdjilka

2022-11-03 15:02 UTC, Sainomori approved these changes
👍

2022-11-03 15:11 UTC, ffaraone requested changes

2022-11-03 15:11 UTC, ffaraone commented on connect/eaas/core/decorators.py
> +        if hasattr(cls, TRANSFORMATION_ATTR_NAME):
I think this if is not needed. If people put the same decorator twice is not our problem.

2022-11-03 15:11 UTC, ffaraone commented on connect/eaas/core/decorators.py
> +            'edit_dialog_ui': edit_dialog_ui,
probably we can set here the fqn of this class like:
```
'class_fqn': f'{cls.__module__}.{cls.__name__}',
```

2022-11-03 15:11 UTC, ffaraone commented on connect/eaas/core/extension.py
> +class TransformationBase(ApplicationBase):
No need to inherit from ApplicationBase.
The Runner will handle the set of transformation starting from the module so the way he get the extension.json descriptor will be starting from the module location.

2022-11-03 15:11 UTC, ffaraone commented on connect/eaas/core/decorators.py
> +        setattr(cls, TRANSFORMATION_ATTR_NAME, [{
It should be just an object not an list of objects.
The runner will iterate over all the classes within a module (the module to which we will refer using setuptools entrypoints) that inherit from TransformationBase to build the list of all transformations

2022-11-03 15:11 UTC, ffaraone commented on connect/eaas/core/extension.py
> +        return getattr(cls, TRANSFORMATION_ATTR_NAME, [])
default should be None (just for validations in the future)

2022-11-03 15:11 UTC, ffaraone commented on connect/eaas/core/proto.py
> +    class_name: str
This should be `edit_dialog_ui`

2022-11-03 15:11 UTC, ffaraone commented on connect/eaas/core/proto.py
> +    method: str
this should be `class_fqn`

2022-11-03 16:33 UTC, ffaraone approved these changes

2022-11-04 09:21 UTC, d3rky approved these changes

2022-11-04 09:28 UTC, merged