LITE-28127: added django filter and pagination utils functions
cloudblue/connect-eaas-core pull request #99
Opened 2023-07-19 15:08 UTC by gab832

2023-07-20 07:33 UTC, ffaraone requested changes

2023-07-20 07:33 UTC, ffaraone commented on connect/eaas/core/contrib/django/rql.py
> +        filter = filter_cls(queryset)
Please rename this variable to `filter_instance`, sonar is not happy with this.

2023-07-20 08:25 UTC, ffaraone submitted a review, later dismissed

2023-11-20 11:09 UTC, Sainomori approved these changes
👍

2023-11-20 11:09 UTC, merged